2013-01-16 01:14:58.004141: ENGINE starting
2013-01-16 01:14:58.006986: ENGINE loading STUDENT ENGINE part 2
2013-01-16 01:14:58.023667: ENGINE loaded player module: OKComputer as player 1
2013-01-16 01:14:58.023914: QUORIDOR ENGINE CLIENT 1.0.5 by Adam Oest initializing
2013-01-16 01:14:58.253157: ENGINE calling STUDENT ENGINE init
2013-01-16 01:14:58.253798: STUDENT ENGINE init call successfully returned
2013-01-16 01:14:58.254058: ENGINE calling init() for player 1
2013-01-16 01:14:58.254673: OKComputer initialized as player 1
2013-01-16 01:14:58.260805: ENGINE GUI accessible at:
https://adelaide.cs.rit.edu/~royale/quoridorui/gameview/gameid.46237/partone.0/apikey.36bc8c65d1d4af66485/public.9be77a12841ce0e419f1afb98f3e6c7fea8d51cb50f645685ddcc/animations.500/
2013-01-16 01:14:58.260980: ENGINE processing move # 1
2013-01-16 01:14:58.261044: ENGINE getting move for player 1 from PRE_MOVE list 
2013-01-16 01:14:58.261059: ENGINE validating player 1 move. Player 1 Wall: [0,2] -> [2,2]
2013-01-16 01:14:58.262003: ENGINE calling STUDENT ENGINE validate_move
2013-01-16 01:14:58.395657: STUDENT ENGINE validate_move call successfully returned
2013-01-16 01:14:58.421736: ENGINE uploading move to web engine
2013-01-16 01:14:58.700532: ENGINE detects correct move validation by STUDENT ENGINE
2013-01-16 01:14:58.710007: ENGINE calling STUDENT ENGINE last_move
2013-01-16 01:14:58.710258: STUDENT ENGINE last_move call successfully returned
2013-01-16 01:14:58.710347: ENGINE finished processing player 1's move
2013-01-16 01:14:58.742007: ENGINE notifying player 1 of last move
2013-01-16 01:14:58.742814: ENGINE finished with next move
2013-01-16 01:14:58.743165: ENGINE processing move # 2
2013-01-16 01:14:58.743312: ENGINE getting move for player 1 from PRE_MOVE list 
2013-01-16 01:14:58.743436: ENGINE validating player 1 move. Player 1 Wall: [0,2] -> [2,2]
2013-01-16 01:14:58.743580: ENGINE calling STUDENT ENGINE validate_move
2013-01-16 01:14:58.743829: ERROR: error() takes exactly 2 arguments (1 given)
2013-01-16 01:14:58.747787: TRACE: 
Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\a\Quoridor_Client_2121\Releases\1.0.5\Python3.2\Model\__init__.py", line 560, in studentEngineCall
  File "/home/wheeler/workspace/quoridor_group/StudentEngines/jak3122/__init__.py", line 342, in validate_move
    Logger.error("Log: Invalid wall placement, overlaps valid wall.\n")
TypeError: error() takes exactly 2 arguments (1 given)

2013-01-16 01:14:58.752049: ERROR: 2013-01-16 01:14:58.751856: ENGINE exiting due to STUDENT ENGINE exception

2013-01-16 01:14:58.752755: TRACE: 
Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\a\Quoridor_Client_2121\Releases\1.0.5\Python3.2\Engine\controller.py", line 246, in nextTurn
  File "C:\Users\Adam\Desktop\a\Quoridor_Client_2121\Releases\1.0.5\Python3.2\Model\__init__.py", line 567, in studentEngineCall
Engine.security.GameException: 2013-01-16 01:14:58.751856: ENGINE exiting due to STUDENT ENGINE exception


2013-01-16 01:14:59.060425: 2013-01-16 01:14:58.751856: ENGINE exiting due to STUDENT ENGINE exception

2013-01-16 01:14:59.067177: ENGINE finished with next move
2013-01-16 01:14:59.067556: ENGINE shutting down
