2013-01-22 23:20:22.435500: ENGINE starting
2013-01-22 23:20:22.441788: ENGINE loading STUDENT ENGINE part 3
2013-01-22 23:20:22.461704: ENGINE loaded player module: OKComputer as player 1
2013-01-22 23:20:22.462279: ENGINE loaded player module: Human as player 2
2013-01-22 23:20:22.462291: QUORIDOR ENGINE CLIENT 1.0.5 by Adam Oest initializing
2013-01-22 23:20:23.931576: ENGINE calling STUDENT ENGINE init
2013-01-22 23:20:23.932035: STUDENT ENGINE init call successfully returned
2013-01-22 23:20:23.932173: ENGINE calling init() for player 1
2013-01-22 23:20:23.932228: ENGINE calling STUDENT ENGINE initialize_player
2013-01-22 23:20:23.932933: OKComputer initialized as player 1
2013-01-22 23:20:23.933249: STUDENT ENGINE initialize_player call successfully returned
2013-01-22 23:20:23.933443: ENGINE calling init() for player 2
2013-01-22 23:20:23.933560: ENGINE calling STUDENT ENGINE initialize_player
2013-01-22 23:20:23.933692: STUDENT ENGINE initialize_player call successfully returned
2013-01-22 23:20:23.948620: ENGINE GUI accessible at:
https://adelaide.cs.rit.edu/~royale/quoridorui/gameview/gameid.69250/partone.0/apikey.36bc8c65d1d4af66485/public.7f9bf69a33d76b4e8331c44e7ecb3f8a981e4b3c50ff6507d0729/animations.500/
2013-01-22 23:20:23.951141: ENGINE calling STUDENT ENGINE next_move
2013-01-22 23:20:23.953630: ENGINE uploading move to web engine
2013-01-22 23:20:26.017399: ERROR: 'StudentEngineModel' object has no attribute 'last_move'
2013-01-22 23:20:26.020958: TRACE: 
Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\a\Quoridor_Client_2121\Releases\1.0.5\Python3.2\Model\__init__.py", line 560, in studentEngineCall
  File "/home/wheeler/workspace/quoridor_group/StudentEngines/jak3122/__init__.py", line 514, in next_move
    playerdata=model.last_move(playerdata,move) #update the board
AttributeError: 'StudentEngineModel' object has no attribute 'last_move'

